NewsApp/Controllers/AuthorsController.cs
using Microsoft.AspNetCore.Mvc;
using NewsApp.Models;
using NewsApp.Services;
using Newtonsoft.Json;
using System.Reflection;

namespace NewsApp.Controllers
{
    public class AuthorsController : Controller
    {
        private readonly IAuthorServices _authorServices;

        public AuthorsController(IAuthorServices authServices)
        {
            _authorServices = authServices;
        }

        [HttpGet]
        public async Task<IActionResult> Index(string? search, string sortType = "UserName", string sortOrder = "asc", int pageSize = 10, int pageNumber = 1)
        {
            var authors = await _authorServices.GetAuthors(search, sortType, sortOrder, pageSize, pageNumber);

            return View(authors);
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegisterViewModel user)
        {
            if (ModelState.IsValid)
            {
                var errorMessage = await _authorServices.Register(user);

                if (string.IsNullOrEmpty(errorMessage))
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, errorMessage);
                    return View(user);
                }
            }

            return View("Register", user);
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel user)
        {
            if (ModelState.IsValid)
            {
                var errorMessage = await _authorServices.Login(user);

                if (string.IsNullOrEmpty(errorMessage))
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, errorMessage);
                    return View(user);
                }
            }

            return View("Login", user);
        }

        [HttpGet]
        public async Task<IActionResult> GetAuthor(string id)
        {
            if (string.IsNullOrEmpty(id))
                return BadRequest("Invalid Author Id");

            var author = await _authorServices.GetAuthorById(id);

            return View("Details", author);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            if (string.IsNullOrEmpty(id))
                return BadRequest("Invalid Author Id");

            var author = await _authorServices.GetAuthorById(id);

            return View(new UpdateAuthorViewModel
            {
                FirstName = author.FirstName,
                LastName = author.LastName,
                UserName = author.UserName,
                Email = author.Email
            });
        }

        [HttpPost]
        public async Task<IActionResult> Edit(string id, UpdateAuthorViewModel updatedAuthor)
        {
            if (string.IsNullOrEmpty(id))
                return BadRequest("Invalid Author Id");

            if (ModelState.IsValid)
            {
                var errorMessage = await _authorServices.UpdateAuthor(id, updatedAuthor);

                if (string.IsNullOrEmpty(errorMessage))
                {
                    return RedirectToAction("Index");
                }
                else {
                    ModelState.AddModelError(string.Empty, errorMessage);
                    return View(updatedAuthor);
                }
            }

            return View("Edit", updatedAuthor);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(string id)
        {
            if (string.IsNullOrEmpty(id))
                return BadRequest("Invalid Author Id");

            var author = await _authorServices.GetAuthorById(id);

            return View(author);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id, AuthorViewModel author)
        {
            if (string.IsNullOrEmpty(id))
                return BadRequest("Invalid Author Id");

            var errorMessage = await _authorServices.DeleteAuthor(id);

            if (string.IsNullOrEmpty(errorMessage))
            {
                return RedirectToAction("Index");
            }
            else
            {
                ModelState.AddModelError(string.Empty, errorMessage);
                return View(author);
            }
        }
    }
}

NewsApp/Controllers/NewsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using NewsApp.Models;
using NewsApp.Services;

namespace NewsApp.Controllers
{
    public class NewsController : Controller
    {
        private readonly INewsServices _newsServices;
        private readonly IAuthorServices _authorServices;

        public NewsController(INewsServices newsServices, IAuthorServices authorServices)
        {
            _newsServices = newsServices;
            _authorServices = authorServices;
        }

        [HttpGet]
        public async Task<IActionResult> Index(string? authorId, string? search, string sortType = "Title", string sortOrder = "asc", int pageSize = 10, int pageNumber = 1)
        {
            var authors = await _authorServices.GetAuthors("", "UserName", "asc", 100, 1);
            ViewBag.Authors = new SelectList(authors.Authors, "Id", "UserName", authorId);
            var news = await _newsServices.GetAllNewsAsync(search, sortType, sortOrder, pageSize, pageNumber);
            if (authorId != null)
            {
                ViewBag.AuthorId = authorId;
                var authorNews = news.News.Where(x => x.Author.Id == authorId);
                news.News = authorNews.ToList();
                news.TotalPages = (int)Math.Ceiling((double)authorNews.Count() / news.PageSize);
                return View(news);
            }            
            return View(news);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var news = await _newsServices.GetNewsByIdAsync(id);
            return View("Details", news);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            if (id == 0)
                return NotFound();

            var news = await _newsServices.GetNewsByIdAsync(id);
            return View(news);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var authors = await _authorServices.GetAuthors("", "UserName", "asc", 100, 1);
            ViewBag.Authors = new SelectList(authors.Authors, "Id", "UserName");
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            if (id == 0)
                return NotFound($"News with ID {id} is not found");

            var news = await _newsServices.GetNewsByIdAsync(id);
            var authors = await _authorServices.GetAuthors("", "UserName", "asc", 100, 1);
            ViewBag.Authors = new SelectList(authors.Authors, "Id", "UserName", news.Author.Id);
            ViewBag.ImageUrl = news.ImageUrl;
            return View(new UpdateNewsViewModel 
            {
                AuthorId = news.Author.Id,
                Description = news.Description,
                Title = news.Title,
                PublicationDate = news.PublicationDate
            });
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, UpdateNewsViewModel news)
        {
            if (id == 0)
                return NotFound($"News with ID {id} is not found");

            if (!IsPublicationDateValid(news.PublicationDate))
            {
                ModelState.AddModelError(string.Empty, "Publication date must be between today and one week from today.");
                return View(news);
            }
            var newsById = await _newsServices.GetNewsByIdAsync(id);
            var authors = await _authorServices.GetAuthors("", "UserName", "asc", 100, 1);
            ViewBag.Authors = new SelectList(authors.Authors, "Id", "UserName", news.AuthorId);
            ViewBag.ImageUrl = newsById.ImageUrl;

            if (ModelState.IsValid)
            {
                var result = await _newsServices.UpdateNewsAsync(id, news);

                if (result)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Something went wrong.");
                    return View(news);
                }
            }

            return View("Edit", news);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateNewsViewModel news)
        {
            var authors = await _authorServices.GetAuthors("", "UserName", "asc", 100, 1);
            ViewBag.Authors = new SelectList(authors.Authors, "Id", "UserName");

            if (!IsPublicationDateValid(news.PublicationDate))
            {
                ModelState.AddModelError(string.Empty, "Publication date must be between today and one week from today.");
                return View(news);
            }

            if (ModelState.IsValid)
            {
                var result = await _newsServices.CreateNewsAsync(news);

                if (result)
                {
                    return RedirectToAction("Index");
                }
                else {
                    ModelState.AddModelError(string.Empty, "Something went wrong.");
                    return View(news);
                }
            }

            return View(news);
        }

        private bool IsPublicationDateValid(DateTime publishedDate)
        {
            DateTime today = DateTime.Today;
            DateTime oneWeekFromToday = today.AddDays(7);

            return publishedDate >= today && publishedDate <= oneWeekFromToday;
        }

        [HttpPost]
        public IActionResult Delete(int id, NewsViewModel news)
        {
            if (id == 0)
                return NotFound();

            var result = _newsServices.DeleteNews(id);

            if (result)
                return RedirectToAction("Index");

            return View(news);
        }
    }
}

NewsApp/Views/Shared/_AuthorsData.cshtml
@model NewsApp.Models.AuthorViewModel

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UserName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IsAuthenticated)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IsAuthenticated)
        </dd>
    </dl>
</div>

NewsApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NewsApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NewsApp.styles.css" asp-append-version="true" />
    <link href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" rel="stylesheet" />
    <link href="~/css/flaty.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">NewsApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Authors" asp-action="Register">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Authors" asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Authors" asp-action="Index">Authors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="News" asp-action="Index">News</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted mt-5">
        <div class="container">
            &copy; 2023 - NewsApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

NewsApp/Views/Shared/_NewsData.cshtml
@model NewsApp.Models.NewsViewModel


<div>
    <hr />
    <div class="row" style="display:inline-block;">
        <img src="@Html.DisplayFor(model => model.ImageUrl)" alt="@Model.Title" style="width:15rem; height:15rem; border-radius:7%; display:inline-block; float:none;">
    </div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            Authors @Html.DisplayNameFor(model => model.Author.UserName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Author.UserName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PublicationDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PublicationDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreationDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreationDate)
        </dd>
    </dl>
</div>